{% set name = "pidly" %}
{% set version = "0.2.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pIDLy-{{ version }}.tar.gz
  sha256: 6c9e77d710c09de6856431869b0cca2bc8ac2de961af82ac8665b38fc535567e

build:
  number: 1003
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - pexpect
    - scipy

test:
  imports:
    - pidly
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/anthonyjsmith/pIDLy
  license: MIT
  license_family: MIT
  license_file: 'LICENSE'
  summary: IDL within Python
  description: Control ITT's IDL (Interactive Data Language) from within Python

extra:
  recipe-maintainers:
    - smithsp
