{% set name = "pIDLy" %}
{% set version = "0.2.7" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  'sha256': '6c9e77d710c09de6856431869b0cca2bc8ac2de961af82ac8665b38fc535567e'

build:
  number: 1003
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True  # [win]

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - numpy
    - pexpect
    - scipy

test:
  imports:
    - pidly

about:
  home: https://github.com/anthonyjsmith/pIDLy
  license: MIT
  license_family: MIT
  license_file: 'LICENSE'
  summary: IDL within Python
  description: Control ITT's IDL (Interactive Data Language) from within Python

extra:
  recipe-maintainers:
    - smithsp
