# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "wMfmWsFcoysBghfdlrV5u3NowPW8RnwGRRui5/6OT16gumbTS6Cora/ixgLdkHzl9bUPsSjV1Vwssfz9BX/7psV8k5/jOtm4z0yMDDE1JX4qDFT86NyPd9OhZSXz/2KtxNrBsEDDqkoDYNPfwTlOnMs/9KlCRvcKXO0r+vTaGZ5xkEu9RjT3MEYT5WFwiQzsqls8+p4gRa7vODQeJzgNycwvd0qZM25i+wgFGF6ADFM3q/gRXRVrWQ9xuW/S2k/UAU9dE8GZsfKUY2UjmpQay1rKbCiT3bsqTkv1CXxvtU9/WLLYvceH0K5UOjOsQlRjPzs8w/scJySrgNMFamTxO3+ffs8Ah/mT1mAYUnI7+UJS867OpMpt5caJp0OAflbesbPq0b6hRg/anmoRd5h/K+lcCqDT1VNDfgLUosfV2lmL4RomgLmVfpExoJc5qEBrUxrOWEVdPPet0Kim8i3Y9vAJItyI5VcCLh07i30mJdhMa2DtoIZm/A1fPIKH5eZEf4Dwl8lvDL0UZqPHbKQLT5fBfa6g25kvYUfidaGJs3Wm2o0FnLcWL/zugweeieJYWiHogXYLc99Ya2mC2i5DFAT/5BVJGFlhqtjgWgawXlCRy5pGcmOQugu8qB7+Z7hGc1JHZcD5pIs2+3+fJvIxvv47wg/i7MmAzBISESxAeaU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
